CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
POSE1_TOKEN_INDEX = -300
POSE2_TOKEN_INDEX = -301
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_POSE1_TOKEN = "<pose1>"
DEFAULT_POSE2_TOKEN = "<pose2>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
DEFAULT_POSE_START_TOKEN = "<pose_start>"
DEFAULT_POSE_END_TOKEN = "<pose_end>"
IMAGE_PLACEHOLDER = "<image-placeholder>"
